#!/bin/bash

# Set to a destination folder to copy files to
DEST="${HOME}/transfers/slide"

make clean
make
[ $? -eq 0 ] && {
  [ -x trim_lslo ] && {
    echo "Trimming comments from optimized LSL script"
    ./trim_lslo
  }
}

[ "$1" == "-c" ] && {
  rm -rf ${DEST}
  mkdir -p ${DEST}

  cp Slider.lslo ${DEST}/Slider
  cp README.txt ${DEST}/README
  cp COPYRIGHT LICENSE ${DEST}
}
